spring:
    config:
        activate:
            on-profile: prod

        datasource:
            url: jdbc:h2:file:./data/testbase;NON_KEYWORDS=user
            driverClassName: org.h2.Driver
            username: sa
            password: password

    liquibase:
        change-log: classpath:config/liquibase/changelog-master.xml
