spring:
    config:
        activate:
            on-profile: dev


    datasource:
        url: jdbc:h2:file:./data/testbase;NON_KEYWORDS=user
        driverClassName: org.h2.Driver
        username: sa
        password: password

    h2:
        console:
            enabled: true
            path: /h2-console

    liquibase:
        change-log: classpath:config/liquibase/changelog-master.xml


